server:
  port: 8080

spring:
  application:
    name: booking-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/skillbridge}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
